export enum ERole {
  DOCTOR = 'DOCTOR',
  ADMIN_DOCTOR = 'ADMIN_DOCTOR',
  PATIENT = 'PATIENT',
  SECRETARY = 'SECRETARY',
  ADMIN = 'ADMIN',
}

export enum EBillingStatus {
  PAID = 'PAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  OVERDUE = 'OVERDUE',
  REFUNDED = 'REFUNDED',
  CANCELED = 'CANCELED',
}

export enum EAppointmentStatus {
  PENDING = 'PENDING',
  FULLFILLED = 'FULLFILLED',
  DONE = 'DONE',
  CANCELED = 'CANCELED',
}
