export enum ERole {
  DEMANDEUR = 'DEMANDEUR',
  VALIDATEUR = 'VALIDATEUR',
  ADMIN = 'ADMIN',
}

export enum ERequestStatus {
  DRAFT = 'DRAFT',
  CANCELED = 'CANCELED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
}
